In [2]:
#Q1:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Check if there is a difference in data type
if list_.__class__ != array_list.__class__:
    print(f"Data type of list_: {list_.__class__}")
    print(f"Data type of array_list: {array_list.__class__}")
else:
    print("No difference in data type.")


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [3]:
#Q2:

# Print data type of each element
print("Data type of elements in list_:")
for elem in list_:
    print(type(elem))

print("\nData type of elements in array_list:")
for elem in array_list:
    print(type(elem))


Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [4]:
#Q3:


# Print data type of each element
print("Data type of elements in list_:")
for elem in list_:
    print(type(elem))

print("\nData type of elements in array_list:")
for elem in array_list:
    print(type(elem))


Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [5]:
#Q4:


num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Shape
print(f"(i) Shape of num_array: {num_array.shape}")

# (ii) Size
print(f"(ii) Size of num_array: {num_array.size}")


(i) Shape of num_array: (2, 3)
(ii) Size of num_array: 6


In [6]:
#Q5:

zeros_array = np.zeros((3, 3))
print("Array of zeros:")
print(zeros_array)



Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:

#Q6:

identity_matrix = np.eye(5)
print("Identity matrix:")
print(identity_matrix)

Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
